on: [push]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: AH_ACCESS_TOKEN=eyJraWQiOiJ4UTVmbFI5NDBiMXdjTW85NFBMUHhHdzFyb1pCSXBTYnFReWlqcWZUc0xzIiwidHlwIjoiSldUIiwiYWxnIjoiUlM1MTIifQ.eyJpc3MiOiJOb3BlIiwiaWF0IjoxNjYxNTA2NjUwLCJqdGkiOiJlZjM3MGQ3Yy05YzczLTRmZWMtYjg4Ny1iZDdkOTRlNTdiOGQiLCJ1c2VyIjp7ImlkIjoiMjQ3ZTZkOGUtYjcwMC00OTQ3LTllZTQtN2E3Yzg5YzY0NmI2IiwiYWNjb3VudF9pZCI6ImY4ODljMzEwLWU4Y2YtNDQ4MS05N2MwLTY3ZTA2ODQ4NWExNiIsImVtYWlsIjoibWloYWlsLnphaGFyb3YrMUBhcHBzYmVycnkuY29tIn19.qVewSd66Xdyal6Z2fp4m8kGLH3Izegdad0i9PLp2dgUqj3rM1EC5pFDz3Rfz-Pq80axhAwubPmnEvAO_PfzqjnJlXI8x0PZx70J4i7nZ7-7Dy1m8cdu5uqd-0xWX5ljx5Gaoysb_doXoQ1352mnAhERuRivPtqEZFugAZlwWjb-kEFRsuTnaFSzFVDvXedSSVVIHMVPfteScjMQp67KXCFcTdFLoJmmS9CJYZcZfK9R5HR-wWFfSSqDdPy_0xi3VUlNyIsrAqPPJFsQ-7ROTNShzxkCz2Y7Fpt0PbxbXyZl-fSu3isyUvyVKKZ3Kuvxn1M8XZRYXv_x1Pi5SRoQynJhebDAZYCIjVbUws6b7iaSyrHti8SDvRyrxaS-Rv5umY7k6v1hXSBqQFsuTBKZrW3cqjObeOJ2evGIFNrANVXMIbu7XOgQYLaCSHYvAXM0ro4tMN5iLl4Tv9r1FloaTZLpk_V9DxyNAZSUlGKMhsThovf5SzMFGQa-Imu8ckAnCBc5c4kEuQIBTxxaMNEw8eOPCBsN8jPUY6uQ1jl0mQT6KNCk8Wctk-HzKo8lZAY-rFsk7JY2R00zjEg-4GlFckL7paj7xtwYMWh_UG86cSntFDwtQhsyuOT4yy_gTCXDkWr-01_r_qgurCBZ13aDrQuk-jmpxxPm0jIQ3gp2zQ1Y TF_ACC=1 go test ./... -v
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
# TODO: enable later
#      - name: golangci-lint
#        uses: golangci/golangci-lint-action@v2
