on: [push]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: AH_ACCESS_TOKEN=replaceMe TF_ACC=1 go test ./... -v
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
# TODO: enable later
#      - name: golangci-lint
#        uses: golangci/golangci-lint-action@v2
